<?php
namespace XT\Core\Cache\Storage\Adapter\Memcached;


class Memcached extends \Zend\Cache\Storage\Adapter\Memcached
{
    public function setOptions($options)
    {

        if (isset($options['dirLevel'])) unset($options['dirLevel']);
        if (isset($options['dirPermission'])) unset($options['dirPermission']);
        if (isset($options['filePermission'])) unset($options['filePermission']);
        if (isset($options['cache_dir'])) unset($options['cache_dir']);


        return parent::setOptions($options); // TODO: Change the autogenerated stub
    }

    public function setItem($key, $value)
    {
        if (CACHE_ON)
            return parent::setItem($key, $value); // TODO: Change the autogenerated stub
        return false;
    }
}