<?
/***
 * @var $this PhpRenderer
 */

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Xuân Thu CMS</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="d-flex p-4 h-100 w-100 bg-dark">
<div class="container align-self-center">
    <div class="card bg-light mb-3" >
        <div class="card-header bg-danger text-light"><h1><?=$this->translate('Not permission granted')?></h1></div>
        <div class="card-body">
            <h4 class="card-title"><?=$this->translate('Contact to administrator')?></h4>
            <p><?=$this->translate('The task does not work because some reasons')?>:</p>
            <ul>
                <li>Not Login</li>
                <li>Not Role</li>
                <li>Resources not exist!</li>
                <?
                if ($mgs != null)
                    echo "<li class='text-danger'>$mgs</li>";
                ?>

            </ul>
        </div>
        <div class="card-footer bg-transparent">
            <a class="btn btn-warning" href="/"><?=$this->translate('Home')?></a>
            <a class="btn btn-success" href="/auth/"><?=$this->translate('Login')?></a></div>
    </div>
</div>
</body>
</html>