<?
/**
 * @var $this PhpRenderer
 */
?>
<div class="p-4 w-100">
    <?=$this->dropdownMenu()->setName('BlockLayout')->render([
        'Layout Edit' => $this->url('admin', ['plugin' => 'layout', 'act' =>'layoutedit']),
        'Holder' => $this->url('admin', ['plugin' => 'layout', 'act' =>'holder']),
        'BlockLayout' => $this->url('admin', ['plugin' => 'layout', 'act' =>'applyblocklayout']),
        'InsertHTML' => $this->url('admin', ['plugin' => 'layout', 'act' =>'eventinserthtml']),
        'Home Slider' => $this->url('admin', ['plugin' => 'layout', 'act' =>'editslide']),
        'PluginView' => $this->url('admin', ['plugin' => 'pluginview']),
        'ListenerGlobal' => $this->url('admin', ['plugin' => 'pluginview', 'act' => 'listenerglobal']),


    ])?>
    <?
    echo $this->pageBreadcrumbs()->setItems([
        'Administrator' => $this->url('admin'),
        'Layout' => $this->url('admin', ['plugin' => 'layout']),
        'BlockLayout' => $this->url('admin', ['plugin' => 'layout', 'act'=>'applyblocklayout']),
        'Edit' => ''
    ])->render();
    ?>


    <div class="p-2">
        <h4>Cấu hình ứng dụng Block HTML vào Layout</h4>
        <div class="btn-group">
             <a class="btn btn-default" href="<?=$this->url('admin', ['plugin'=>'layout'])?>">Các block HTML</a>
         </div>
        <?
        $item = &$this->event->get_array();
        ?>
        <form method="POST">
            <div class="p-1 bg-light">
                <div class="form-group">
                    <label>Controller+Action - Trang hiện thị</label>
                    <?=$this->controlaction?>
                </div>
                <div class="form-group">
                    <label>Holder key (vị trí block)</label>
                    <?=$this->holder?>
                </div>

                <div class="form-group">
                    <label>Tên Block</label>
                    <?=$this->selectfile?>
                </div>
                <div class="form-group">
                    <label>Trạng thái</label>
                    <input name="active" type="checkbox" <?if ($item['active']) echo 'checked="checked"'?>/>


                </div>
                <div class="form-group">
                    <button name="action" class="btn btn-primary">Save</button>  <input name="action" class="btn btn-danger" value="Del" type="submit" />
                </div>

            </div>
        </form>


    </div>

</div>
















