<?
/**
 * @var $this PhpRenderer
 */
?>
<div class="p-4 w-100">
    <?=$this->partial('dropdown_breadcrumbs',
        [
            'listplugins' => $listplugins,
            'currentNameplugin' => $currentNameplugin,
            'listactions' => $listactions,
            'currentNameaction' => $currentNameaction
        ])?>

    <?

        //**Get Controller List
        $controls= XT\Core\Common\Common::$sm->get('config')['controllers'];
        $controller = [];
        foreach ($controls as $key => $cc) {
            if (!isset($controller[$key]))
                $controller[$key] = [];
            foreach ($cc as $k=>$c)
                $controller[$key][$k] =  $c;

        }

        $ctrllist = [];
        foreach ($controller as $ctrl)
        {
            $ctrllist = array_merge($ctrllist, $ctrl);
        }

        $existcontroller = function ($ctrl) use ($ctrllist)
        {
            if ($ctrl == 'ALL') return true;
            return isset($ctrllist[$ctrl]);
        };

    ?>

    <div class="p-1 w-100">
        <h5>Block Layout</h5>


        <?
        $list = $this -> listeventblock;//->get_array();
        $color = 0;
        $control = '';
        $action = '';
        $getclass = function($c,$a) use (&$color, &$control,&$action, $existcontroller)
        {
            if (!$existcontroller($c))
                return 'bg-info text-dark';


            if (($c != $control) || ($a != $action))
            {
                $control = $c;
                $action = $a;
                $color++;
                if ($color > 1) $color = 0;
            }
            switch ($color)
            {
                case 0:
                    return 'bg-light';
                    break;
                case 1:
                    return '';
                    break;
            }


        };
        $ctrl = '';
        ?>

        <div class="row ml-1 mr-1" style="font-weight: bold;">
            <div class="col-3">Controller</div>
            <div class="col-3">Action</div>
            <div class="col-4">Block HTML</div>
            <div class="col-2">PlaceHolder</div>
        </div>

        <?foreach ($list as &$item) :?>
            <?if ($ctrl != $item['Controller']) :?>
                <?$ctrl = $item['Controller']?>

            <?endif?>
            <div class="row  ml-1 mr-1 <?=$getclass($item['Controller'],$item['Action'])?>" style="border-bottom: 1px solid whitesmoke; padding: 2px;">

                <div class="col-3"><a href="<?=$this->url('admin', ['plugin'=>'layout','id'=>$item['id'], 'act' => 'applyblocklayoutedit' ])?>" style="color:<? if($item['active']) echo '#333'; else echo 'silver';?>"><?=$item['Controller']?></a></div>
                <div class="col-3"><?=$item['Action']?></div>

                <div class="col-4"><?=$item['Block']?></div>
                <div class="col-2"><code><?=$item['placeholder']?></code></div>
            </div>
        <?endforeach?>

        <hr>
        <div>
            <form method="POST">
                <a class="btn btn-success" href="<?=$this->url('admin', ['plugin'=>'layout', 'act' => 'applyblocklayoutedit'])?>">Thêm mới</a>
                <input class="btn btn-success" type="submit" value="saveconfig" />
            </form>
        </div>

    </div>

</div>