<?

use Ichte\Core\Uicoms\Slide;
/**
 * @var PhpRenderer $this
 * @var PhpRenderer $render
 * @var $form Slide\SlideForm
 * @var $render \Zend\View\Renderer\PhpRenderer
 * formRow - formElement
 * @var $formhelper Zend\Form\View\Helper\Form
 *
 */
$slide = $form->slide;

$render = $this;
$render->headLink()->prependStylesheet($this->basePath('/public/css/home.css'));
$formhelper = $render->form();



?>

<div class="p-2">
<?=$this->dropdownMenu()->setName('Home Slider')->render([
    'Layout Edit' => $this->url('admin', ['plugin' => 'layout', 'act' =>'layoutedit']),
    'Holder' => $this->url('admin', ['plugin' => 'layout', 'act' =>'holder']),
    'BlockLayout' => $this->url('admin', ['plugin' => 'layout', 'act' =>'applyblocklayout']),
    'InsertHTML' => $this->url('admin', ['plugin' => 'layout', 'act' =>'eventinserthtml']),
    'Home Slider' => $this->url('admin', ['plugin' => 'layout', 'act' =>'editslide']),
    'PluginView' => $this->url('admin', ['plugin' => 'pluginview']),
    'ListenerGlobal' => $this->url('admin', ['plugin' => 'pluginview', 'act' => 'listenerglobal']),

])?>
<?
echo $this->pageBreadcrumbs()->setItems([
    'Administrator' => $this->url('admin'),
    'Layout' => $this->url('admin', ['plugin' => 'layout']),
    'Home Slider' => $this->url('admin', ['plugin' => 'layout', 'act'=>'eventinserthtml']),
    //'Edit' => ''
])->render();
?>

</div>
<?
$form->setAttribute('action',$render->url('admin',['plugin'=>'layout','act' =>'editslide' ,'id'=>$form->idpagecurrent]));
$form->prepare();

?>
<div class="card w-100 p-2">
    <div class="card-block">
        <?

        echo $formhelper->openTag($form);
        ?>
        <div class="m-b-1">
            <ul class="nav nav-tabs">
                <?foreach ($slide->pages as $page):?>
                    <li class="nav-item">
                        <a href="<?=$render->url('admin',['plugin'=>'layout','act'=>'editslide' ,'id' =>$page[Slide\Slide::ID]])?>"
                           class="nav-link<?=($form->idpagecurrent == $page[Slide\Slide::ID])?" active":""?>"><?=$slide->getTitle($page)?></a>
                    </li>
                <?endforeach;?>
            </ul>
        </div>


        <?if($form->idpagecurrent != null):?>
            <div class="form-group">
                <?=$this->formRow($form->get(Slide\Slide::TITLE))?>
            </div>
            <div class="form-group">
                <?=$this->formRow($form->get(Slide\Slide::CONTENT))?>

            </div>
            <div class="form-group">
                <?=$this->formRow($form->get(Slide\Slide::IMG))?>


            </div>

            <?=$render->browandinsertImg(Slide\Slide::IMG)?>


        <?endif;?>
        <hr>
        <div class="form-group">

            <?if($form->idpagecurrent != null):?>
                <?=$this->formRow($form->get('xoatrang'))?>

            <?endif;?>
            <?=$this->formRow($form->get('addnew'))?>
            <?=$this->formRow($form->get('save'))?>

        </div>




        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<?=$form->slide->render($this)?>
<?
$this->showHtmlEditcode('slideContent');
?>
