<?
/**
 * @var $this PhpRenderer
 */
?>
<div class="p-4 w-100">
    <?=$this->partial('dropdown_breadcrumbs',
        [
            'listplugins' => $listplugins,
            'currentNameplugin' => $currentNameplugin,
            'listactions' => $listactions,
            'currentNameaction' => $currentNameaction
        ])?>

    <div class="p-2 w-100">
        <h5>Insert HTML to Placeholder</h5>
        

        <?
        $list = $this -> listeventblock;
        $color = 0;
        $control = '';
        $action = '';
        $getclass = function($c,$a) use (&$color, &$control,&$action)
        {
            if (($c != $control) || ($a != $action))
            {
                $control = $c;
                $action = $a;
                $color++;
                if ($color > 1) $color = 0;
            }
            switch ($color)
            {
                case 0:
                    return 'bg-light';
                    break;
                case 1:
                    return '';
                    break;
            }


        };

        $controls= XT\Core\Common\Common::$sm->get('config')['controllers'];
        $controller = [];
        foreach ($controls as $key => $cc) {
            if (!isset($controller[$key]))
                $controller[$key] = [];
            foreach ($cc as $k=>$c)
                $controller[$key][$k] =  $c;

        }
        $ctrllist = [];
        foreach ($controller as $ctrl)
        {
            $ctrllist = array_merge($ctrllist, $ctrl);
        }

        $existcontroller = function ($ctrl) use ($ctrllist)
        {
            return isset($ctrllist[$ctrl]);
        };

        $ctrl = '';



        ?>
        <table class="table">
            <thead>
            <tr>
                <th>Controller</th>
                <th>Action</th>
                <th>Event</th>
                <th>Block HTML</th>
            </tr>
            </thead>



            <?foreach ($list as &$item) :?>
                <?if ($ctrl != $item['Controller']) :?>
                    <?$ctrl = $item['Controller']?>
                <?endif?>

                <tr class="<?=$getclass($item['Controller'],$item['Action'])?>">
                    <td><a href="<?=$this->url('admin', ['plugin'=>'layout','act' => 'eventinserthtmledit', 'id'=>$item['id']])?>"
                           style="color:<? if($item['active']) echo 'black'; else echo 'silver';?>">
                            <?=$item['Controller']?></a>
                        <?if (!($existcontroller($item['Controller']))) echo "<i class=\"fa fa-eye-slash\" aria-hidden=\"true\"></i>";?>

                    </td>
                    <td><?=$item['Action']?></td>
                    <td><?=$item['Event']?></td>
                    <td><?=$item['Block']?></td>
                </tr>


            <?endforeach?>
        </table>



        <div style="padding: 20px; text-align: right;">
            <form method="POST">
                <a class="btn btn-warning" href="<?=$this->url('admin', ['plugin'=>'layout', 'act' => 'eventinserthtmladd'])?>">+ Add new Event</a>
                <input class="btn btn-success" type="submit" value="Export Config" />
            </form>
        </div>
    </div>

</div>