<?
/**
 * @var $this PhpRenderer
 * @var $item XT\Core\System\Placeholder\Placeholder
 * @var $form \XT\Core\Admin\Layout\Form\FormHolder
 */
?>
<div class="p-4 w-100">

    <?=$this->partial('dropdown_breadcrumbs',
        [
            'listplugins' => $listplugins,
            'currentNameplugin' => $currentNameplugin,
            'listactions' => $listactions,
            'currentNameaction' => $currentNameaction
        ])?>

    <?
    $form->setAttribute('action', $this->url('admin', ['plugin' => 'options', 'act' => 'addgroup']));
    $form->setAttribute('class', 'form');
    $form->prepare();
    ?>

    <h3>Edit Placeholder</h3>

    <form method="POST">
            <div class="form-group">
                <label><?=$this->translate('Name')?></label>
                <?=$this->formrow($form->get('name'))?>
            </div>
            <div class="form-group">
                <label><?=$this->translate('Description')?></label>
                <?=$this->formrow($form->get('description'))?>
                <?=$this->formhidden($form->get($form->getNameCsrf()))?>
                <?=$this->formhidden($form->get('placeholder_id'))?>
            </div>


            <div class="form-group">
                <button class="btn btn-success btn-sm" name="action" type="submit" value="Save"><?=$this->translate('Save')?></button>
                <button class="btn btn-danger btn-sm" name="action" type="submit" value="Delete"><?=$this->translate('Delete')?></button>
            </div>


    </form>

</div>


