<?php
/**
 * @var PhpRenderer $this
 */
$csrflayoutedit = new \Zend\Form\Element\Csrf('csrflayoutedit',['csrf_options'=>['timeout'=>'1200']] );


?>

<div class="p-2 w-100">
    <?=$this->partial('dropdown_breadcrumbs',
        [
            'listplugins' => $listplugins,
            'currentNameplugin' => $currentNameplugin,
            'listactions' => $listactions,
            'currentNameaction' => $currentNameaction
        ])?>
    <form method="POST">
        <?=$this->formhidden($csrflayoutedit)?>
        <code><?=$this->fileedit?> : Allway backup file before update</code>
        <input style="display: none;" class="form-control" name="file" style="width: 50%;" value="<?=$this->fileedit?>" type="text" readonly="true" />
        <textarea id="filecontent" name="filecontent" class="form-control" style="width: 100%; min-height: 500px;" spellcheck="false"><?=$this->filecontent?></textarea>
        <div class="form-group pt-4">
            <button type="submit" name="action" value="Save" class="btn btn-success">Save</button>
            <button type="submit" name="action" value="Delete" class="btn btn-danger">Delete</button>
        </div>
        <?$this->enableCodeEdit('filecontent')?>
    </form>
</div>