<?
/**
 * @var $this PhpRenderer
 */

?>
<div class="p-4 w-100">
    <?=$this->partial('dropdown_breadcrumbs',
        [
            'listplugins' => $listplugins,
            'currentNameplugin' => $currentNameplugin,
            'listactions' => $listactions,
            'currentNameaction' => $currentNameaction
        ])?>


<h3>Placeholders - <?=$this->translate('place send event while render HTML')?></h3>
<div class="list-group w-100">
    <?foreach ($this->listevent as $ev):?>
        <a href="<?=$this->url('admin', ['plugin'=>'layout','act'=>'placeholder','id'=>$ev['placeholder_id']])?>" class="list-group-item">
            <h4 class="list-group-item-heading"><?=$ev['name']?></h4>
            <p class="list-group-item-text"><?=$ev['description']?></p>
        </a>
    <?endforeach?>
</div>


<div style="padding: 10px;">
    <a class="btn btn-success" href="<?=$this->url('admin', ['plugin' => 'layout', 'act' =>'newholder'])?>"><?=' + '.$this->translate('Add')?></a>
</div>

</div>