<?php

namespace XT\Core\Cache\Storage\Adapter\Filesystem;


class Filesystem extends \Zend\Cache\Storage\Adapter\Filesystem
{
    public function setItem($key, $value)
    {
        if (CACHE_ON)
            return parent::setItem($key, $value); // TODO: Change the autogenerated stub
        return false;
    }

}