<?php
/***
 * @var $this PhpRenderer
 */
use XT\Core\Common\Common;
use XT\Core\System\KeyView;

Common::setCharsetUtf8();

$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath('public/img/favicon.ico')]);


echo $this->doctype(),PHP_EOL;
echo '<html>
<head>
';
echo $this->headMeta(),PHP_EOL;
echo $this->headTitle(),PHP_EOL;
echo $this->headLink(),PHP_EOL;
echo $this->headScript(),PHP_EOL;
echo $this->headStyle(),PHP_EOL;
echo '</head>
<body>
';
$this->renderPlace(KeyView::HEADER); echo PHP_EOL;

echo "<div ", Common::getBags()->Container,">";
$this->renderPlace(KeyView::NAVSIDEBAR); echo PHP_EOL;
$this->renderPlace(KeyView::CONTENT); echo PHP_EOL;
$this->renderPlace(KeyView::CONTENTASIDE); echo PHP_EOL;
echo "</div>";


$this->renderPlace(KeyView::FOOTER); echo PHP_EOL;
echo $this->inlineScript();
echo '</body>
</html>';
?>